---

# Meta
name: mangonada
description: Personal use image
base-image: ghcr.io/wayblueorg/niri
image-version: latest # Wayblue only supports "Latest" tag

# Modules list
modules:
  - from-file: modules/mangonada-base.yml
  - from-file: modules/mangonada-dms.yml
  - from-file: modules/mangonada-mangowm.yml
  - from-file: modules/mangonada-flatpaks.yml
  - from-file: modules/mangonada-brew.yml # Enabling Homebrew on image
  - from-file: modules/mangonada-fonts.yml # Adding fonts
