# Opinionated default config to get you started

## Required for graphical-session services (the shell, etc.) to function
exec-once=dbus-update-activation-environment --systemd --all
exec-once=systemctl --user start mango-session.target

## basic binds, here if you need them
### Super + T: spawn terminal (foot)
bind=SUPER,t,spawn,foot
### Super + q: kill window
bind=SUPER,q,killclient
### Super + Space: Launcher (TODO: replace with noctalia-shell IPC equivalent)
# bind=SUPER,space,spawn,<noctalia-launcher-cmd>
### Super + r: reload mango config
bind=SUPER,r,reload_config
### Super + m: quit mango
bind=SUPER,m,quit

### The "opinions" part of the "opinionated" config
## "turn off silly defaults"
new_is_master=0
enable_hotarea=0
warpcursor=1
sloppyfocus=1
axis_bind_apply_timeout=100
drag_tile_to_tile=1
enable_floating_snap=0
snap_distance=30

## no animations
animations=0

## no gaps
gappih=0
gappiv=0
gappoh=0
gappov=0
borderpx=1
no_border_when_single=1

## no fun colors
focuscolor=0x005577ff
